// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231128104008_SeedItemTable")]
    partial class SeedItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TodoApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 28, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7260),
                            Description = "Devi farlo per forza mi dispiace",
                            IsActive = true,
                            IssueDate = new DateTime(2023, 11, 30, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7260),
                            Title = "Portare a spasso il cane",
                            UpdatedAt = new DateTime(2023, 11, 28, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7260)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 28, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7270),
                            Description = "A meno che tu non voglia esplodere..",
                            IsActive = true,
                            IssueDate = new DateTime(2023, 11, 29, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7270),
                            Title = "Controllare il gas",
                            UpdatedAt = new DateTime(2023, 11, 28, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7270)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 28, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7270),
                            Description = "Non sei ricco :(",
                            IsActive = true,
                            IssueDate = new DateTime(2023, 11, 30, 14, 50, 8, 174, DateTimeKind.Utc).AddTicks(7270),
                            Title = "Mettere da parte dei soldi",
                            UpdatedAt = new DateTime(2023, 11, 28, 10, 40, 8, 174, DateTimeKind.Utc).AddTicks(7270)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
